server:
  port: 8080
spring:
  application:
    name: abri-tech-restaurant-order
  datasource:
    url: jdbc:mysql://localhost:3306/maleda_db1
    username: root
    password: e@113177
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    generate-ddl: true
    show-sql: true

    hibernate:
      ddl-auto=update:

      ddl-auto=create:
